[package]
name = "ucf-tcf-port"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1"
ucf-attn-controller = { path = "../ucf-attn-controller" }
ucf-predictive-coding = { path = "../ucf-predictive-coding" }
ucf-sandbox = { path = "../ucf-sandbox" }
ucf-types = { path = "../ucf-types" }
