[package]
name = "ucf-commit"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1"
ucf-crypto = { path = "../ucf-crypto" }
ucf-types = { path = "../ucf-types" }
ucf_protocol = { package = "ucf-protocol", path = "../../../ucf-protocol" }
