[package]
name = "ucf-ncde"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1"
ucf-coupling = { path = "../ucf-coupling" }
ucf-types = { path = "../ucf-types" }
ucf-spikebus = { path = "../ucf-spikebus" }
