[package]
name = "ucf-nsr"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1"
ucf-cde-scm = { path = "../../../causal/crates/ucf-cde-scm" }
ucf-sandbox = { path = "../../../../core/crates/ucf-sandbox" }
ucf-spikebus = { path = "../../../../core/crates/ucf-spikebus" }
ucf-structural-store = { path = "../../../../core/crates/ucf-structural-store" }
ucf-types = { path = "../../../../core/crates/ucf-types" }
