[package]
name = "ucf-archive-firewood"
version = "0.1.0"
edition = "2021"

[features]
default = []
archive-firewood = []

[dependencies]
ucf-archive-store = { workspace = true }
ucf-types = { path = "../../../../core/crates/ucf-types" }
