[package]
name = "ucf-fold"
version = "0.1.0"
edition = "2021"

[dependencies]
ucf-crypto = { path = "../ucf-crypto" }
ucf-types = { path = "../ucf-types", features = ["serde"] }
serde = { workspace = true }
serde-big-array = "0.5"
sha2 = "0.10"
