[package]
name = "biophys_governance"
version = "0.1.0"
edition = "2021"

[dependencies]
biophys_core = { path = "../biophys_core" }
ucf = { package = "ucf-protocol", path = "../../vendor/ucf-protocol-main" }
