[package]
name = "biophys_solver"
version = "0.1.0"
edition = "2021"

[dependencies]
biophys_core = { path = "../biophys_core" }

[features]
biophys = []
biophys-l4 = ["biophys"]
biophys-l4-synapses = ["biophys-l4"]
