[package]
name = "microcircuit_cerebellum_pop"
version = "0.1.0"
edition = "2021"

[dependencies]
dbm_core = { path = "../dbm_core" }
microcircuit_cerebellum_stub = { path = "../microcircuit_cerebellum_stub" }
microcircuit_core = { path = "../microcircuit_core" }
